config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root "courses#index"

  resources :courses do
    member do
      get :shelf
    end
  end

  mount ApiRoot => ApiRoot::PREFIX
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :courses
end

app/models/api_access_token.rb
class ApiAccessToken < ApplicationRecord
  belongs_to :user

  before_create :generate_keys

  private
  def generate_keys
    begin
      self.key = SecureRandom.urlsafe_base64(30).tr('_-', 'xx')
    end while ApiAccessToken.where(key: key).any?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :admin
  has_many :orders
  has_many :users, through: :orders


  enum currency: {TWD: 0, USD: 1, JPY: 2}
  enum category: {國文: 0, 英文: 1, 數學: 2, 自然: 3}

  validates :name, presence: true
  validates :duration, presence:true, numericality:{ less_than_or_equal_to: 30 }

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :courses, through: :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :find_course, only: [:edit, :update, :destroy, :shelf]

  def index
    if current_admin
      @courses = Course.all
    else
      @courses = Course.where(state: 'true')
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = current_admin.courses.build(course_params)
    if @course.save
      redirect_to courses_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to courses_path
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to courses_path
  end

  def shelf
    if @course.state
      @course.update(state: false)
    else
      @course.update(state: true)
    end
    redirect_to courses_path
  end

  private
  def course_params
    params.require(:course).permit(:name, :theme, :currency, :price, :url, :describe, :duration, :category, :start_time, :end_time, :state)
  end

  def find_course
    @course = current_admin.courses.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "登入", new_session_path(resource_name), class:"w-full block text-blue-500 border-2 border-blue-500 hover:bg-blue-100 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "註冊", new_registration_path(resource_name), class:"w-full block text-blue-500 border-2 border-blue-500 hover:bg-blue-100 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center"  %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "忘記密碼", new_password_path(resource_name), class:"  text-blue-500 font-medium text-sm px-5 py-2.5"  %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |f| %>
  <div class="min-h-screen md:px-20 pt-6">
    <div class="rounded-md px-6 py-10 max-w-2xl mx-auto">
      <h1 class="text-center text-2xl font-bold text-gray-500 mb-10"><%= btn%></h1>
      <div class="space-y-4">
        <div class='fields'>
          <%= f.label :name, '名稱', class:"text-lx font-serif" %> 
          <%= f.text_field :name, class:"w-full ml-2 outline-none py-1 px-2 text-md border-2 rounded-md"%> 
        </div>
        <div class='fields'>
          <%= f.label :theme, '主題', class:"text-lx font-serif" %> 
          <%= f.text_field :theme, class:"w-full ml-2 outline-none py-1 px-2 text-md border-2 rounded-md"%> 
        </div>
        <div class='fields'>
          <%= f.label :currency, '幣別', class:"text-lx font-serif" %> 
          <%= f.select :currency, options_for_select(Course.currencies.map {|key, value| [key, Course.currencies.key(value)]}, @course.currency), class:"w-full ml-2 outline-none py-1 px-2 text-md border-2 rounded-md"%> 
        </div>
        <div class='fields'>
          <%= f.label :price, '價格', class:"text-lx font-serif" %> 
          <%= f.text_field :price, class:"w-full ml-2 outline-none py-1 px-2 text-md border-2 rounded-md"%> 
        </div>
        <div class='fields'>
          <%= f.label :category, '類型', class:"text-lx font-serif" %> 
          <%= f.select :category, options_for_select(Course.categories.map{|key, value| [key, Course.categories.key(value)]}, @course.category), class:"w-full ml-2 outline-none py-1 px-2 text-md border-2 rounded-md"%> 
        </div>
        <div class='fields'>
          <%= f.label :url, '連結', class:"text-lx font-serif" %> 
          <%= f.text_field :url, class:"w-full ml-2 outline-none py-1 px-2 text-md border-2 rounded-md"%> 
        </div>
        <div class='fields'>
          <%= f.label :describe, '描述', class:"text-lx font-serif" %> 
          <%= f.text_area :describe, class:"w-full ml-2 outline-none py-1 px-2 text-md border-2 rounded-md"%> 
        </div>
        <div class='fields'>
          <%= f.label :duration, '課程可使用效期(不得超過30天)', class:"text-lx font-serif" %> 
          <%= f.text_field :duration, class:"w-full ml-2 outline-none py-1 px-2 text-md border-2 rounded-md"%> 
        </div>
        <div class='action'>
          <% if course.id %>
            <div class="inline px-6 py-3 mx-2 rounded-md text-lg font-semibold <%= course.state ? 'bg-gray-100 text-gray-400' : 'bg-blue-600 text-blue-100' %>">
              <%= link_to "上架", shelf_course_path(course.id) %>
            </div>
            <div class="inline px-6 py-3 mx-2 rounded-md text-lg font-semibold <%= course.state ? 'bg-blue-600 text-blue-100' : 'bg-gray-100 text-gray-400' %>">
              <%= link_to "下架", shelf_course_path(course.id) %>
            </div>
          <% end %>
          <%= f.submit btn, class:"px-6 py-2 mx-auto rounded-md text-lg font-semibold text-blue-100 bg-blue-600"%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>修改課程</h1>

<%= render "form", course: @course, btn: "修改課程" %>

app/views/courses/index.html.erb
<div class="bg-white p-8 rounded-md w-full">
	<div class=" flex items-center justify-between pb-6">
    <h1 class="text-gray-600 font-semibold">課程列表</h1>
    <div class="flex items-center justify-between">
      <div class="lg:ml-40 ml-10 space-x-8">
        <% if current_admin %>
          <%= link_to "新增課程", new_course_path, class:"bg-blue-500 px-4 py-2 rounded-md text-white font-semibold"%>
        <% end %>

        <% if current_user || current_admin %>
          <%= link_to '修改密碼', edit_registration_path(:user), class:"px-4 py-2 rounded-md text-blue-500 border-2 border-blue-500 font-semibold"%>
          <%= link_to '登出', destroy_user_session_path, :method => :delete, class:"px-4 py-2 rounded-md text-blue-500 border-2 border-blue-500 font-semibold"%> 
        <% else %>
          <%= link_to '會員登入', new_session_path(:user), class:"bg-blue-500 px-4 py-2 rounded-md text-white font-semibold"%>
          <%= link_to '管理員登入', new_session_path(:admin), class:"bg-blue-500 px-4 py-2 rounded-md text-white font-semibold" %>
        <% end %>
      </div>
		</div>
	</div>
	<div>
    <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
      <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
        <table class="min-w-full leading-normal">
          <thead>
            <tr class="border-b-2 border-gray-300 bg-gray-300">
              <th class="px-5 py-3 border-b-2 text-left text-xs font-semibold tracking-wider">名稱</th>
              <th class="px-5 py-3 border-b-2 text-left text-xs font-semibold tracking-wider">描述</th>
              <th class="px-5 py-3 border-b-2 text-left text-xs font-semibold tracking-wider">了解更多</th>
              <% if current_admin %>
                <th class="px-5 py-3 border-b-2 text-left text-xs font-semibold tracking-wider">是否上架</th>
                <th class="px-5 py-3 border-b-2 text-left text-xs font-semibold tracking-wider"></th>
                <th class="px-5 py-3 border-b-2 text-left text-xs font-semibold tracking-wider"></th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% @courses.each do |course| %>
              <tr class="border-b">
                <td class="pl-5 py-5 text-sm"><%= course.name %></td>
                <td class="px-5 py-5 text-sm"><%= course.describe %></td>
                <td><%= link_to '詳細內容',course_path(course.id), class:"text-sm transition duration-150 hover:bg-gray-400 font-semibold py-2 px-4"%></td>
                <% if current_admin %>
                  <td class="pl-5 py-5 text-sm"><%= course.state %></td>
                  <td><%= link_to "修改", edit_course_path(course.id), class:"text-sm transition duration-150 hover:bg-gray-200 bg-gray-300 font-semibold py-2 px-4"%></td>
                  <td><%= link_to "刪除", course_path(course.id), method: 'delete', data: {confirm: '確認刪除?'}, class:"text-sm transition duration-150 hover:bg-gray-200 bg-gray-300 font-semibold py-2 px-4"%></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/courses/new.html.erb
<h1>新增課程</h1>

<%= render "form", course: @course, btn: "新增課程" %>

app/views/courses/show.html.erb
<div class="flex items-center p-10 w-full h-full bg-white">
	<div class="border-t border-b pt-16 grid grid-cols-2 gap-8">
    <div class="flex flex-col">
      <div class="flex flex-col gap-4">
        <h1 class="capitalize text-1xl font-extrabold">課程介紹</h1>
        <h2 class="capitalize text-3xl font-extrabold"><%= @course.name %></h2>
        <h3 class="text-3xl"><%= @course.price %><%= @course.currency %></h3>
        <p class="text-sm text-gray-500	">主題：<%= @course.theme %></p>
        <p class="text-sm text-gray-500	">類型：<%= @course.category %></p>
        <p class="text-sm text-gray-500	">課程可使用效期：<%= @course.duration %>天</p>
        <p class="text-sm text-gray-500	">課程描述：<%= @course.describe %></p>
        <div class="flex items-center gap-4 my-6 cursor-pointer ">
          <div class="bg-blue-600 px-5 py-3 text-white rounded-lg w-2/4 text-center">購買課程</div>
        </div>
      </div>
    </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HaSi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "登入", new_session_path(resource_name), class:"w-full block text-blue-500 border-2 border-blue-500 hover:bg-blue-100 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "註冊", new_registration_path(resource_name), class:"w-full block text-blue-500 border-2 border-blue-500 hover:bg-blue-100 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center"  %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "忘記密碼", new_password_path(resource_name), class:"  text-blue-500 font-medium text-sm px-5 py-2.5"  %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>